[package]
name = "container_traits"
version = "0.1.0"
edition = "2021"

[dependencies]
utils = { path="../utils" }

paste = "1.0.14"
nalgebra = { version = "0.33", optional = true }
num-traits= "0.2.15"
thiserror = "2.0.7"

[features]
nalgebra_support = ["dep:nalgebra"]
