[package]
name = "utils"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib"]

[dependencies]
derive_more = { version = "1.0.0", features = ["full"]}

paste = "1.0.14"
num-traits= "0.2.15"
# serde = { version = "1.0", features = ["derive"] }