[package]
name = "utils"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["lib"]

[dependencies]
derive_more = { version = "2.0.1", features = ["full"]}

paste = "1.0.15"
num-traits= "0.2.15"
# serde = { version = "1.0", features = ["derive"] }